### ISSUE TITLE
Make a universal release that works on any recent Java version

### ISSUE THREAD

**Issue by tnici** [pangaea-data-publisher/qualianon#12]
There were reported installation problems on MacOS: https://github.com/pangaea-data-publisher/qualianon/issues/11

**Comment by fdschneider** [comment]
I'd like to upvote this issue. 
The current installation instructions refer to [Oracle Java 8](https://www.java.com/en/download/), which is only free for personal use and developmental use, but requires a commercial license for production use. The charges for commercial licenses are per employee (totally unrealistic in my case). 
A release AND installation instructions for other Java versions (e.g. [OpenJDK](https://openjdk.org/)) would be a prerequisite for being able to use Qualianon in the future. 
Thanks!

**Comment by sschlerka** [comment]
Dear @jrennstich and @fdschneider, the current version 1.5.0 is running on Amazon Corretto OpenJDK 17, which is licensed under GPLv2 with CPE and is thus free to use in any scenario.

**Comment by yjeanrenaud** [comment]
it still seems to get some issues with that.
running on macos, my student get's the following:
```
% java --version
openjdk 17.0.15 2025-04-15 LTS
OpenJDK Runtime Environment Corretto-17.0.15.6.1 (build 17.0.15+6-LTS) 
OpenJDK 64-Bit Server VM Corretto-17.0.15.6.1 (build 17.0.15+6-LTS, mixed mode, sharing) 
```
we also tried oracle's openjdk without any luck, but correto 17 should be the one you recommend, isn't it?
when running it does not finde the JavaFX module:

```
% java -jar quali-anon-1.5.0.jar 
Mai 27, 2025 1:54:31 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2767c9ec'
Loading library prism_es2 from resource failed: 
java.lang.UnsatisfiedLinkError: 
/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib: 
dlopen(/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib,
0x0001): tried: 
'/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need
(x86_64h)))
java.lang.UnsatisfiedLinkError: 
/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib: 
dlopen(/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib,
0x0001): tried: 
'/Users/myuser/.openjfx/cache/17.0.6/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need
(x86_64h)))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at
java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at
java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at
java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1970)
	at
com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at
com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at
com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at
com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at
java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at
com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:840)
Loading library prism_sw from resource failed: 
java.lang.UnsatisfiedLinkError: 
/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib: 
dlopen(/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib,
0x0001): tried: 
'/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need
(x86_64h)))
java.lang.UnsatisfiedLinkError: 
/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib: 
dlopen(/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib,
0x0001): tried: 
'/Users/myuser/.openjfx/cache/17.0.6/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need
(x86_64h)))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at
java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at
java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at
java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1970)
	at
com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at
com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at
com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at
com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at
java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at
com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:840)
Graphics Device initialization failed for :  es2, sw Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at
com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at
com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Error initializing
QuantumRenderer: no suitable pipeline found
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at
com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at
com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at
com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by jrennstich** [comment]
I am unable to make this work. I tried several approaches to run the OpenJDK17 to no avail. If anybody has any instructions, how to make this work on a Mac (that uses M1 or M2 etc.) I would greatly appreciate that. This seems to be the main problem here on my end.
